#
# * Config
# * Stores static configuration and project info
# *
# * Copyright © Michael O'Rourke (@caleorourke)
# * Released under the MIT license
#

# ==============================
# Project
# ==============================

github:
  name:       Proof
  tagline:    "Design proofs and artifacts...FTW."
  owner:      "Michael O'Rourke (@caleorourke)"
  license:    MIT

# ==============================
# Social
# ==============================

keywords:     "css,framework,github,github pages,html5,proof,jekyll,liquid,markdown,redcarpet"

# ==============================
# Markdown
# ==============================

markdown:     redcarpet
redcarpet:
  extensions: ["autolink",
               "fenced_code_blocks",
               "lax_spacing",
               "smart",
               "tables"]

# ==============================
# Server
# ==============================

baseurl:      /proof
permalink:    pretty
exclude:      [".gitignore",
               "Gruntfile.js",
               "less",
               "plugins",
               "node_modules",
               "package.json"]
